version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todo_app_with_django
    env_file:
      - .env
    environment:
      DJANGO_SECRET_KEY: "django-insecure-8k*4^2lx0zsbz$&o&#4ze*-o230!d^%0f#ui&akraycjz#su9i"
    volumes:
      - .:/todo_app_with_django
    ports:
      - "8000:8000"